"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, Check, CircleDot, ShieldCheck } from "lucide-react";
import type { PlaygroundScenario } from "@/lib/playground";
import { getPlaygroundDataset } from "@/lib/playground";
import { TfBadge, TfLabel, TfPanel } from "@/components/ui/tf-primitives";
const scenarios = [
  ["c2_quieting", "C2 quieting"],
  ["lotl_gradual", "LOTL gradual fade"],
  ["gnss_jam", "GNSS jamming"],
  ["normal_with_fade", "Normal transient dip"],
  ["mixed", "Mixed laboratory set"],
] as const;
const stageText: Record<string, string> = {
  traffic: "Curated pattern — not live traffic.",
  signals: "Signal extraction is represented by the normalized series.",
  behavior: "Behavioral change is visible in the series shape.",
  deviation: "Conceptual only; production detector is isolated.",
  detection: "Not executed in the website playground.",
  evidence: "Not generated by the production engine.",
  confidence: "Not generated by the production engine.",
  attack: "Not generated by the production engine.",
  timeline: "Relative sample timeline.",
};
export function PlaygroundClient() {
  const [scenario, setScenario] = useState<PlaygroundScenario>("c2_quieting");
  const [data, setData] = useState<ReturnType<typeof getPlaygroundDataset> | null>(null);
  const [error, setError] = useState<string | null>(null);
  async function choose(next: PlaygroundScenario) {
    setScenario(next);
    setError(null);
    try {
      const r = await fetch("/api/playground", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ scenario: next }),
      });
      const body = await r.json();
      if (!r.ok) throw new Error(body.error);
      setData(body);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unable to load dataset.");
    }
  }
  const path = useMemo(
    () =>
      data?.values
        ?.map(
          (v: number, i: number) =>
            `${i ? "L" : "M"} ${(i / (data.values.length - 1)) * 100} ${92 - v * 78}`,
        )
        .join(" ") || "",
    [data],
  );
  return (
    <div className="space-y-8">
      <TfPanel raised className="p-5 sm:p-7">
        <TfLabel>Curated laboratory data</TfLabel>
        <div className="mt-3 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <h2 className="text-2xl font-semibold">Choose a behavioral pattern</h2>
            <p className="mt-2 max-w-2xl text-sm leading-7 text-[var(--tf-text-muted)]">
              Deterministic web visualizations derived from the engine&apos;s documented signal-generator
              shapes. They are not live detections.
            </p>
          </div>
          <TfBadge tone="warning">production engine: isolated</TfBadge>
        </div>
        <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
          {scenarios.map(([id, label]) => (
            <button
              key={id}
              type="button"
              aria-pressed={scenario === id}
              onClick={() => void choose(id)}
              className={`rounded-lg border p-4 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--tf-signal)] ${scenario === id ? "border-[var(--tf-signal)] bg-[var(--tf-signal-soft)]" : "border-[var(--tf-line)] bg-[var(--tf-panel)]"}`}
            >
              <span className="font-mono text-[10px] uppercase text-[var(--tf-text-subtle)]">
                {id}
              </span>
              <span className="mt-2 block text-sm font-semibold">{label}</span>
            </button>
          ))}
        </div>
      </TfPanel>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(280px,.7fr)]">
        <TfPanel className="p-5 sm:p-7">
          <div className="flex items-center justify-between">
            <div>
              <TfLabel>Behavioral signal</TfLabel>
              <h2 className="mt-2 text-xl font-semibold">{data?.label ?? "Select a pattern"}</h2>
            </div>
          </div>
          <div className="mt-6 rounded-lg border border-[var(--tf-line)] bg-[var(--tf-ink)] p-3">
            {data ? (
              <svg
                viewBox="0 0 100 100"
                className="h-64 w-full"
                role="img"
                aria-labelledby="signal-title signal-desc"
              >
                <title id="signal-title">Curated behavioral signal</title>
                <desc id="signal-desc">
                  Normalized source-generator pattern, not a production detection result.
                </desc>
                <path
                  d="M0 92H100"
                  stroke="currentColor"
                  className="text-[var(--tf-line)]"
                  vectorEffect="non-scaling-stroke"
                />
                <path
                  d={path}
                  fill="none"
                  stroke="currentColor"
                  className="text-[var(--tf-signal)]"
                  strokeWidth="1.5"
                  vectorEffect="non-scaling-stroke"
                />
              </svg>
            ) : (
              <div className="flex h-64 items-center justify-center text-sm text-[var(--tf-text-subtle)]">
                Choose a pattern above.
              </div>
            )}
          </div>
          {data ? (
            <div className="mt-4 flex flex-wrap gap-2">
              <TfBadge tone="neutral">source-pattern visualization</TfBadge>
              <TfBadge tone="neutral">rule: {data.rule}</TfBadge>
              <TfBadge tone="warning">no detection verdict</TfBadge>
            </div>
          ) : null}
          {data ? (
            <p className="mt-4 text-xs leading-6 text-[var(--tf-text-subtle)]">{data.note}</p>
          ) : null}
          {error ? (
            <div
              role="alert"
              className="mt-4 flex gap-2 rounded-lg border border-[var(--tf-danger)]/30 p-4 text-sm"
            >
              <AlertTriangle className="size-4" />
              {error}
            </div>
          ) : null}
        </TfPanel>
        <TfPanel className="p-5 sm:p-7">
          <TfLabel>Pipeline</TfLabel>
          <div className="mt-5 space-y-2">
            {(data?.stages ?? []).map(
              (stage, i) => (
                <div key={stage.id} className="flex gap-3">
                  <div className="flex flex-col items-center">
                    <div
                      className={`rounded-full border p-1 ${stage.state === "not-executed" ? "border-[var(--tf-line)]" : "border-[var(--tf-signal)] text-[var(--tf-signal)]"}`}
                    >
                      {stage.state === "not-executed" ? (
                        <CircleDot className="size-3" />
                      ) : (
                        <Check className="size-3" />
                      )}
                    </div>
                    {i < (data?.stages.length ?? 0) - 1 ? (
                      <div className="h-full min-h-4 w-px bg-[var(--tf-line)]" />
                    ) : null}
                  </div>
                  <div className="pb-3">
                    <p className="text-sm font-medium">{stage.label}</p>
                    <p className="mt-1 text-xs leading-5 text-[var(--tf-text-subtle)]">
                      {stageText[stage.id]}
                    </p>
                  </div>
                </div>
              ),
            )}
          </div>
        </TfPanel>
      </div>
      <TfPanel raised className="p-5 sm:p-7">
        <div className="flex gap-4">
          <ShieldCheck className="size-5 text-[var(--tf-signal)]" />
          <div>
            <TfLabel>Security boundary</TfLabel>
            <h2 className="mt-2 text-lg font-semibold">
              No uploads. No arbitrary code. No production detector.
            </h2>
            <p className="mt-3 max-w-3xl text-sm leading-7 text-[var(--tf-text-muted)]">
              Only a small validated scenario identifier is accepted. The public demo does not
              accept PCAPs, arbitrary arrays, URLs, commands or files, and does not send untrusted
              data to the production detection API.
            </p>
          </div>
        </div>
      </TfPanel>
    </div>
  );
}
