import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, ShieldCheck } from "lucide-react";
import { ConversionLink } from "@/components/analytics/conversion-link";
import { PageShell } from "@/components/layout/page-shell";
import { TfBadge, TfPanel } from "@/components/ui/tf-primitives";

export const metadata: Metadata = {
  title: "Pricing and commercial paths",
  description:
    "ThreatFade commercial packaging from open-core adoption through team operations, assessment, pilot, enterprise and managed detection.",
  alternates: { canonical: "/pricing" },
};

const plans = [
  { name: "Community", price: "$0", cadence: "forever", audience: "Researchers, developers and security practitioners", body: "The open-core detection engine and reproducible technical evaluation surface.", items: ["Core detection engine", "Offline / local analysis", "PCAP analysis", "Core detection packs", "Evidence and ATT&CK context", "CLI / API and documentation"], cta: "Run the source", href: "https://github.com/LloydCoder/tinlance-threatfade", external: true, featured: false },
  { name: "Pro", price: "$49", cadence: "/month · $490/year", audience: "Individual practitioners", body: "A low-friction commercial step for people who need a private, repeatable ThreatFade workflow.", items: ["Private workspace", "Saved investigations", "Evidence export", "Commercial usage allowance", "Priority product guidance"], cta: "Ask about Pro", href: "mailto:hello@tinlance.com?subject=ThreatFade%20Pro", external: false, featured: false },
  { name: "Team", price: "$299", cadence: "/month · $2,990/year", audience: "Small security teams", body: "Shared investigation and governance foundations for teams operationalizing behavioral-fade detection.", items: ["Shared organization workspace", "RBAC and tenant boundary", "Investigation workflow", "Audit history", "Evidence and disposition workflow", "Documented integration paths"], cta: "Discuss Team", href: "mailto:hello@tinlance.com?subject=ThreatFade%20Team", external: false, featured: true },
  { name: "Enterprise", price: "$25k+", cadence: "/year · scoped", audience: "Mid-market and enterprise security programs", body: "Annual platform commitment for deployment, governance, integrations and operational requirements.", items: ["Enterprise identity / SSO", "Advanced RBAC and tenancy", "Audit and governance", "Deployment architecture", "Enterprise integration scope", "Contracted support / SLA options"], cta: "Start evaluation", href: "/enterprise", external: false, featured: false },
] as const;

const ladder = [["01", "Community", "$0", "Adopt and challenge the engine."], ["02", "Pro", "$49/mo", "Turn repeat usage into a private workflow."], ["03", "Team", "$299/mo", "Operationalize shared investigations."], ["04", "Assessment", "$5k+", "Find evidence-backed detection gaps."], ["05", "Paid Pilot", "$7.5k–$15k", "Validate value in a defined environment."], ["06", "Enterprise", "$25k+/yr", "Operationalize at organizational scale."], ["07", "Managed", "$3.5k–$15k+/mo", "Buy ongoing detection expertise."]] as const;

const faqs = [["Is ThreatFade open source?", "Yes. The open-core detection engine remains the technical trust and distribution layer. Commercial packaging adds operationalization, governance, deployment and expertise rather than crippling the core detection thesis."], ["Is Enterprise pricing per seat?", "No. The intended model is an annual platform commitment shaped by deployment scope, analysis requirements, integrations, support and security requirements rather than arbitrary seat counts."], ["What does the $5,000+ assessment buy?", "A scoped Detection Gap Assessment covering the agreed telemetry and architecture, ThreatFade analysis, evidence examples, coverage gaps, prioritized recommendations and a pilot design. Larger environments are quoted above the starting price."], ["Are the prices contractual?", "No. Public prices are starting standards for planning. Final quotes reflect scope, deployment, usage, support and integration complexity."], ["Does ThreatFade replace a SIEM or SOAR?", "No. ThreatFade is positioned as a specialized detection and investigation layer that can hand structured results to existing security operations systems."]] as const;

export default function PricingPage() {
  return <PageShell eyebrow="Commercial paths" title="Open at the detection core. Premium where operational value begins." description="ThreatFade is not packaged as generic SaaS. The commercial ladder follows the buyer's progression from technical adoption to evidence, pilot, enterprise operation and managed expertise.">
    <div className="grid gap-4 lg:grid-cols-4">
      {plans.map((plan) => <TfPanel key={plan.name} raised={plan.featured} className="flex flex-col p-6 sm:p-7"><div className="flex items-center justify-between gap-3"><TfBadge tone={plan.featured ? "signal" : "neutral"}>{plan.name}</TfBadge>{plan.featured && <span className="text-[10px] font-mono uppercase tracking-[0.14em] text-[var(--tf-signal)]">Core commercial tier</span>}</div><div className="mt-6 text-3xl font-semibold tracking-[-0.04em]">{plan.price}</div><div className="mt-1 text-xs font-mono uppercase tracking-[0.12em] text-[var(--tf-text-subtle)]">{plan.cadence}</div><h2 className="mt-5 text-lg font-semibold">{plan.audience}</h2><p className="mt-3 min-h-20 text-sm leading-6 text-[var(--tf-text-muted)]">{plan.body}</p><ul className="mt-5 space-y-3 border-t border-[var(--tf-line)] pt-5 text-sm">{plan.items.map((item) => <li key={item} className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-[var(--tf-signal)]" /><span>{item}</span></li>)}</ul>{plan.external ? <a href={plan.href} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-medium text-[var(--tf-signal)]">{plan.cta}<ArrowRight className="size-4" /></a> : plan.href.startsWith("/") ? <Link href={plan.href} className="mt-7 inline-flex items-center gap-2 text-sm font-medium text-[var(--tf-signal)]">{plan.cta}<ArrowRight className="size-4" /></Link> : <ConversionLink href={plan.href} event={plan.name === "Pro" ? "request_evaluation" : "request_enterprise"} source={`pricing_${plan.name.toLowerCase()}`} className="mt-7 inline-flex items-center gap-2 text-sm font-medium text-[var(--tf-signal)]">{plan.cta}<ArrowRight className="size-4" /></ConversionLink>}</TfPanel>)}
    </div>
    <section className="mt-12"><div className="mb-6 flex items-center gap-2"><ShieldCheck className="size-4 text-[var(--tf-signal)]" /><span className="text-xs font-mono uppercase tracking-[0.14em] text-[var(--tf-text-subtle)]">Value ladder</span></div><div className="grid gap-px overflow-hidden rounded-2xl border border-[var(--tf-line)] bg-[var(--tf-line)] md:grid-cols-7">{ladder.map(([number, name, price, body]) => <article key={name} className="bg-[var(--tf-panel)] p-5"><div className="font-mono text-[10px] text-[var(--tf-text-subtle)]">{number}</div><h3 className="mt-6 font-semibold">{name}</h3><div className="mt-1 text-xs text-[var(--tf-signal)]">{price}</div><p className="mt-3 text-xs leading-5 text-[var(--tf-text-muted)]">{body}</p></article>)}</div></section>
    <section className="mt-12 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><TfPanel className="p-6 sm:p-8"><TfBadge tone="signal">High-intent path</TfBadge><h2 className="mt-4 text-2xl font-semibold">Assessment → Pilot → Enterprise</h2><p className="mt-4 text-sm leading-7 text-[var(--tf-text-muted)]">For organizations that need evidence before committing to a platform, the commercial wedge is a scoped Detection Gap Assessment. A successful assessment produces the acceptance criteria for a paid pilot; the pilot ends with a measured enterprise decision.</p><div className="mt-6 flex flex-wrap gap-3"><ConversionLink href="/assessment" event="request_assessment" source="pricing" className="tf-button tf-button-primary">Detection Gap Assessment</ConversionLink><ConversionLink href="/pilot" event="request_pilot" source="pricing" className="tf-button">Paid pilot</ConversionLink></div></TfPanel><TfPanel className="p-6 sm:p-8"><TfBadge tone="neutral">Trust boundary</TfBadge><h2 className="mt-4 text-2xl font-semibold">Evidence, not invented proof.</h2><ul className="mt-5 space-y-4 text-sm leading-6 text-[var(--tf-text-muted)]"><li><strong className="text-[var(--tf-text)]">Open-source capability</strong> — inspectable in the repositories.</li><li><strong className="text-[var(--tf-text)]">Validated capability</strong> — backed by repository tests and documented validation scope.</li><li><strong className="text-[var(--tf-text)]">Experimental capability</strong> — clearly labelled research or optional layers.</li><li><strong className="text-[var(--tf-text)]">Professional services</strong> — assessment, pilot, managed operations and custom engineering are scoped separately.</li></ul></TfPanel></section>
    <section className="mt-12"><h2 className="text-2xl font-semibold">Frequently asked</h2><div className="mt-5 divide-y divide-[var(--tf-line)] rounded-2xl border border-[var(--tf-line)]">{faqs.map(([question, answer]) => <details key={question} className="group p-5"><summary className="cursor-pointer list-none font-medium">{question}</summary><p className="mt-3 max-w-3xl text-sm leading-7 text-[var(--tf-text-muted)]">{answer}</p></details>)}</div></section>
    <section className="mt-12 rounded-2xl border border-[color-mix(in_srgb,var(--tf-signal)_20%,var(--tf-line))] bg-[var(--tf-signal-soft)] p-7 sm:p-9"><TfBadge tone="signal">Need a technical evaluation?</TfBadge><h2 className="mt-4 text-2xl font-semibold">Start with the question, not a generic demo.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[var(--tf-text-muted)]">Bring a detection scenario, evidence question or deployment constraint. We can scope the appropriate commercial path without representing unvalidated capabilities as production guarantees.</p><div className="mt-6 flex flex-wrap gap-3"><ConversionLink href="mailto:hello@tinlance.com?subject=ThreatFade%20commercial%20evaluation" event="request_evaluation" source="pricing_bottom" className="tf-button tf-button-primary">Request evaluation</ConversionLink><Link href="/enterprise" className="tf-button">Enterprise architecture</Link></div></section>
  </PageShell>;
}
